### PR TITLE
feat: upgrade to supported go version and migrate to Terraform Plugin SDK v2

### PR DESCRIPTION
**Pull request by galuszkak**

### CODE REVIEW

**Comment by galuszkak** [comment]
Hi @niuzhenguo @ShiChangkuo ,

The tests are passing. I couldn't figure out why website is not building. I didn't change anything around website configuration itself so I'm guessing that something changed maybe in terraform-website repo?

**Comment by galuszkak** [comment]
Hi @niuzhenguo @ShiChangkuo  ,

Kind reminder, would you have time to look into it?

**Comment by niuzhenguo** [comment]
@galuszkak Please check out the travis-ci issue

**Comment by galuszkak** [comment]
@niuzhenguo master build is failing with exact same issue. So per my understanding this is unrelated to my chnages. 

Can you give me a hint, because this is documentation building issue a d I'm not sure how this works.

**Comment by niuzhenguo** [comment]
@galuszkak I'm sorry to say that, we don't plan to continue to update this repo anymore, should use huaweicloud provider instead.

**Comment by galuszkak** [comment]
@niuzhenguo will Huawei cloud provider support private cloud (Huawei Cloud Stack?)

**Comment by niuzhenguo** [comment]
@galuszkak To my understanding, the future version of Huawei Cloud Stack should have the same API with Huawei Cloud.

**Pull request closed without merging**
